name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Repository'yi clone'la
    - name: Repository'yi Clone'la
      uses: actions/checkout@v3

    # Python'u kur
    - name: Python 3.9'u Kur
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Ortam değişkenlerini tanımla
    - name: Ortam Değişkenlerini Tanımla
      env:
        ACCOUNT_SID: ${{ secrets.account_sid }}
        AUTH_TOKEN: ${{ secrets.auth_token }}
        WHATSAPP_NUMBER: ${{ secrets.WHATSAPP_NUMBER }}
      run: |
        echo "Ortam değişkenleri ayarlandı."

    # Flask Gereksinimlerini Kur
    - name: Flask Gereksinimlerini Kur
      run: |
        pip install -r requirements.txt

    # Flask Uygulamasını Çalıştır
    - name: Flask Uygulamasını Çalıştır
      env:
        ACCOUNT_SID: ${{ secrets.account_sid }}
        AUTH_TOKEN: ${{ secrets.auth_token }}
        WHATSAPP_NUMBER: ${{ secrets.WHATSAPP_NUMBER }}
      run: |
        python app.py
